-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-14 10:32:08 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clenstvi 
    ( 
     kanal_id    VARCHAR2 (36)  NOT NULL , 
     uzivatel_id VARCHAR2 (36)  NOT NULL , 
     role        VARCHAR2 (32)  NOT NULL 
    ) 
;

ALTER TABLE clenstvi 
    ADD 
    CHECK (role IN ('admin', 'clen')) 
;

ALTER TABLE clenstvi 
    ADD CONSTRAINT clenstvi_PK PRIMARY KEY ( kanal_id, uzivatel_id ) ;

CREATE TABLE hodnoceni 
    ( 
     uzivatel_id     VARCHAR2 (36)  NOT NULL , 
     video_id        VARCHAR2 (36)  NOT NULL , 
     komentar        VARCHAR2 (2048) , 
     pocet_hvezdicek NUMBER (3,1)  NOT NULL , 
     datum_publikace DATE  NOT NULL 
    ) 
;

ALTER TABLE hodnoceni 
    ADD 
    CHECK (pocet_hvezdicek IN (1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5)) 
;

ALTER TABLE hodnoceni 
    ADD CONSTRAINT hodnoceni_PK PRIMARY KEY ( uzivatel_id, video_id ) ;

CREATE TABLE kanal 
    ( 
     id    VARCHAR2 (36)  NOT NULL , 
     nazev VARCHAR2 (256)  NOT NULL , 
     slug  VARCHAR2 (36) 
    ) 
;

ALTER TABLE kanal 
    ADD CONSTRAINT kanal_PK PRIMARY KEY ( id ) ;

ALTER TABLE kanal 
    ADD CONSTRAINT kanal_slug_UN UNIQUE ( slug ) ;

CREATE TABLE oauth_konfigurace 
    ( 
     id                VARCHAR2 (36)  NOT NULL , 
     logo_url          VARCHAR2 (1024) , 
     nazev             VARCHAR2 (64)  NOT NULL , 
     authorization_url VARCHAR2 (128)  NOT NULL , 
     scopes            CLOB  NOT NULL , 
     token_url         VARCHAR2 (128)  NOT NULL , 
     user_info_url     VARCHAR2 (128) , 
     client_id         VARCHAR2 (128)  NOT NULL , 
     client_secret     VARCHAR2 (128)  NOT NULL 
    ) 
;

ALTER TABLE oauth_konfigurace 
    ADD CONSTRAINT oauth_konfigurace_PK PRIMARY KEY ( id ) ;

ALTER TABLE oauth_konfigurace 
    ADD CONSTRAINT oauth_konfigurace_nazev_UN UNIQUE ( nazev ) ;

CREATE TABLE sledovani 
    ( 
     video_id    VARCHAR2 (36)  NOT NULL , 
     uzivatel_id VARCHAR2 (36)  NOT NULL , 
     id          VARCHAR2 (36)  NOT NULL , 
     cas_od      INTEGER  NOT NULL , 
     cas_do      INTEGER , 
     session_id  VARCHAR2 (36) 
    ) 
;

ALTER TABLE sledovani 
    ADD CONSTRAINT sledovani_PK PRIMARY KEY ( id ) ;

CREATE TABLE uzivatel 
    ( 
     id                   VARCHAR2 (36)  NOT NULL , 
     jmeno                VARCHAR2 (1024)  NOT NULL , 
     avatar_url           VARCHAR2 (1024) , 
     role                 VARCHAR2 (32)  NOT NULL , 
     oauth_konfigurace_id VARCHAR2 (36)  NOT NULL 
    ) 
;

ALTER TABLE uzivatel 
    ADD 
    CHECK (role IN ('admin', 'uzivatel')) 
;

ALTER TABLE uzivatel 
    ADD CONSTRAINT uzivatel_PK PRIMARY KEY ( id ) ;

CREATE TABLE video 
    ( 
     id                    VARCHAR2 (36)  NOT NULL , 
     nazev                 VARCHAR2 (2048)  NOT NULL , 
     popis                 VARCHAR2 (2048) , 
     datum_publikace       DATE , 
     nahledovy_obrazek_url VARCHAR2 (1024) , 
     manifest_url          VARCHAR2 (1024) , 
     kanal_id              VARCHAR2 (36)  NOT NULL 
    ) 
;

ALTER TABLE video 
    ADD CONSTRAINT video_PK PRIMARY KEY ( id ) ;

ALTER TABLE clenstvi 
    ADD CONSTRAINT clenstvi_kanal_FK FOREIGN KEY 
    ( 
     kanal_id
    ) 
    REFERENCES kanal 
    ( 
     id
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE clenstvi 
    ADD CONSTRAINT clenstvi_uzivatel_FK FOREIGN KEY 
    ( 
     uzivatel_id
    ) 
    REFERENCES uzivatel 
    ( 
     id
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE hodnoceni 
    ADD CONSTRAINT hodnoceni_uzivatel_FK FOREIGN KEY 
    ( 
     uzivatel_id
    ) 
    REFERENCES uzivatel 
    ( 
     id
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE hodnoceni 
    ADD CONSTRAINT hodnoceni_video_FK FOREIGN KEY 
    ( 
     video_id
    ) 
    REFERENCES video 
    ( 
     id
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE sledovani 
    ADD CONSTRAINT sledovani_uzivatel_FK FOREIGN KEY 
    ( 
     uzivatel_id
    ) 
    REFERENCES uzivatel 
    ( 
     id
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE sledovani 
    ADD CONSTRAINT sledovani_video_FK FOREIGN KEY 
    ( 
     video_id
    ) 
    REFERENCES video 
    ( 
     id
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE uzivatel 
    ADD CONSTRAINT uzivatel_oauth_konfigurace_FK FOREIGN KEY 
    ( 
     oauth_konfigurace_id
    ) 
    REFERENCES oauth_konfigurace 
    ( 
     id
    ) 
;

ALTER TABLE video 
    ADD CONSTRAINT video_kanal_FK FOREIGN KEY 
    ( 
     kanal_id
    ) 
    REFERENCES kanal 
    ( 
     id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
